font=JetBrainsMono Nerd Font:size=16
# font=Terminess Nerd Font:size=16
pad=6x6

# [key-bindings]
# clipboard-copy=Control+c XF86Copy
# clipboard-paste=Control+v XF86Paste

[colors-dark]
alpha=0.96
background=1F1F28
foreground=DCD7BA

# Normal colors
regular0=16161D
regular1=C34043
regular2=76946A
regular3=C0A36E
regular4=7E9CD8
regular5=957FB8
regular6=6A9589
regular7=C8C093

# Bright colors
bright0=727169
bright1=E82424
bright2=98BB6C
bright3=E6C384
bright4=7FB4CA
bright5=D27E99
bright6=7AA89F
bright7=DCD7BA

# Selection and cursor
selection-foreground=1F1F28
selection-background=C8C093
urls=7E9CD8
cursor=1F1F28 C8C093
